#ifndef PPS_SOCKET_DEFINE_H
#define PPS_SOCKET_DEFINE_H

#define SOCK_ERR_UNKNOWN -1
#define SOCK_ERR_ADDR_INVALID 1
#define SOCK_ERR_CREATE_FAILED 2
#define SOCK_ERR_BIND_FAILED 3
#define SOCK_ERR_LISTEN_FAILED 4
#define SOCK_ERR_CTX_FULL 5

#define SOCK_ERR_CONN_FAILED 6
#define SOCK_ERR_CONN_REFUSED 7
#define SOCK_ERR_CONN_NETUNREACH 8
#define SOCK_ERR_TIMEOUT 9

// sock event
#define SOCK_POLLEVT_IN 1
#define SOCK_POLLEVT_OUT 2

#endif // !PPS_SOCKET_DEFINE_H

